"""Health sync provider contracts."""

from app.services.health_sync.fake_withings import FakeWithingsError, FakeWithingsProvider
from app.services.health_sync.models import (
    DEFAULT_CURSOR_OVERLAP,
    HealthDirtyState,
    HealthFetchResult,
    HealthOAuthTokens,
    HealthProviderCapabilities,
    HealthProviderCategory,
    HealthProviderSlug,
    HealthResourceType,
    HealthSourceRecord,
    HealthSyncCursor,
    HealthSyncError,
    HealthSyncErrorKind,
    HealthSyncOutcome,
    HealthSyncStatus,
    HealthTombstone,
    WITHINGS_PROVIDER_CAPABILITIES,
    build_fallback_external_id,
    resolve_external_id,
)
from app.services.health_sync.oauth_state import (
    ConsumedOAuthState,
    IssuedOAuthState,
    OAuthStateError,
    OAuthStateStore,
    get_oauth_state_store,
    reset_oauth_state_store_for_tests,
)
from app.services.health_sync.provider import HealthSyncProvider
from app.services.health_sync.notifications import (
    WithingsNotificationError,
    WithingsNotificationResult,
    ingest_withings_notification,
)
from app.services.health_sync.sync import (
    DEFAULT_SYNC_MAX_ATTEMPTS,
    DEFAULT_SYNC_RETRY_AFTER_CAP_SECONDS,
    HealthSyncCursorError,
    apply_cursor_overlap,
    sync_claimed_dirty_category,
    sync_connection_resource,
    sync_connection_resource_safely,
    sync_dirty_categories,
)
from app.services.health_sync.reconciliation import (
    DEFAULT_RECONCILIATION_BACKFILL_WINDOW,
    HealthReconciliationSummary,
    reconcile_connections,
)
from app.services.health_sync.repository import (
    HealthConnectionRecord,
    HealthDirtyCategory,
    HealthSyncRepository,
    HealthWebhookReceipt,
    StoredHealthSourceRecord,
    repository_for,
)
from app.services.health_sync.tokens import (
    HealthConnectionTokens,
    HealthTokenStoreError,
    load_connection_tokens,
    refresh_connection_tokens,
    store_connection_tokens,
)
from app.services.health_sync.withings import WithingsAdapterError, WithingsProvider
from app.services.health_sync.worker import (
    HealthSyncWorker,
    HealthSyncWorkerResult,
    health_sync_resource_types,
)

__all__ = [
    "ConsumedOAuthState",
    "DEFAULT_RECONCILIATION_BACKFILL_WINDOW",
    "DEFAULT_SYNC_MAX_ATTEMPTS",
    "DEFAULT_SYNC_RETRY_AFTER_CAP_SECONDS",
    "DEFAULT_CURSOR_OVERLAP",
    "FakeWithingsError",
    "FakeWithingsProvider",
    "HealthConnectionRecord",
    "HealthDirtyCategory",
    "HealthDirtyState",
    "HealthFetchResult",
    "HealthOAuthTokens",
    "HealthProviderCapabilities",
    "HealthProviderCategory",
    "HealthProviderSlug",
    "HealthReconciliationSummary",
    "HealthResourceType",
    "HealthSourceRecord",
    "HealthConnectionTokens",
    "HealthSyncCursor",
    "HealthSyncCursorError",
    "HealthSyncError",
    "HealthSyncErrorKind",
    "HealthSyncOutcome",
    "HealthSyncProvider",
    "HealthSyncRepository",
    "HealthSyncStatus",
    "HealthSyncWorker",
    "HealthSyncWorkerResult",
    "HealthTokenStoreError",
    "HealthTombstone",
    "HealthWebhookReceipt",
    "IssuedOAuthState",
    "OAuthStateError",
    "OAuthStateStore",
    "StoredHealthSourceRecord",
    "WITHINGS_PROVIDER_CAPABILITIES",
    "WithingsNotificationError",
    "WithingsNotificationResult",
    "WithingsAdapterError",
    "WithingsProvider",
    "build_fallback_external_id",
    "get_oauth_state_store",
    "ingest_withings_notification",
    "apply_cursor_overlap",
    "load_connection_tokens",
    "refresh_connection_tokens",
    "repository_for",
    "reset_oauth_state_store_for_tests",
    "resolve_external_id",
    "sync_claimed_dirty_category",
    "sync_connection_resource",
    "sync_connection_resource_safely",
    "sync_dirty_categories",
    "store_connection_tokens",
    "reconcile_connections",
    "health_sync_resource_types",
]
